apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanu-mongo
  namespace: thanu-ns
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      thanu: sri 
  template:
    metadata:
      labels:
        thanu: sri
    spec:
      containers:
        - name: thanu-mongo
          image: mongo
          ports:
            - containerPort: 3015  
          resources:
            requests: 
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"     
          env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: thanu-secret 
                key: MONGO_URI    
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: thanu-secret 
                key: SESSION_SECRET
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: thanu-secret 
                key: PORT        