apiVersion: v1
kind: Secret
metadata:
  name: thanu-secret 
  namespace: thanu-ns
type: Opaque
stringData:
  MONGO_URI: mongodb://localhost:27017/AFF-Docker
  PORT: 3015
  SESSION_SECRET: your-secret-key 